apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with (default .Values.application.global.annotations .Values.application.producer.annotations) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: hyperswitch-producer-v1o107o0
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ default .Values.application.global.progressDeadlineSeconds .Values.application.producer.progressDeadlineSeconds }}
  replicas: {{ default .Values.application.global.replicas .Values.application.producer.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.application.producer.labels.app }}
      version: v1o107o0
  strategy:
    {{- with (default .Values.application.global.strategy .Values.application.producer.strategy) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.producer.labels.app }}
        version: v1o107o0
      annotations:
        checksum/producer-config: {{ include (print $.Template.BasePath "/producer/configmap.yaml") . | sha256sum }}
        checksum/producer-secret: {{ include (print $.Template.BasePath "/producer/secret.yaml") . | sha256sum }}
        checksum/misc-secrets: {{ include (print $.Template.BasePath "/misc/secrets.yaml") . | sha256sum }}
        checksum/misc-config: {{ include (print $.Template.BasePath "/misc/configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- with (default .Values.application.global.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution .Values.application.producer.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution) }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      initContainers:
        {{- include "postgresql.initContainer.check.ready" . | nindent 8 }}
        {{- if .Values.redisMiscConfig.checkRedisIsUp.initContainer.enable }}
        {{- include "redis.initContainer.check.ready" . | nindent 8 }}
        {{- end }}
      containers:
        - name: hyperswitch-producer
          image: {{ .Values.services.producer.image }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - pkill -15 node
          env:
          {{- include "generic.envs" . | nindent 12 }}
          {{- include "postgresql.secrets.envs" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: producer-cm-{{ .Release.Name }}
            - secretRef:
                name: producer-secret-{{.Release.Name }}
            - secretRef:
                name: hyperswitch-secrets
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /local/config/production.toml
              name: hyperswitch-config
              subPath: production.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: hyperswitch-router-role
      terminationGracePeriodSeconds: {{ .Values.application.producer.terminationGracePeriodSeconds }}
      volumes:
        - configMap:
            defaultMode: 420
            name: hyperswitch-config
          name: hyperswitch-config
